### ISSUE TITLE
极1S 用mtd刷机变砖。如何正确刷机？

### ISSUE THREAD

**Issue by chintj** [rssnsj/openwrt-hc5761#10]
极1S 用mtd刷机变砖。如何正确刷机？

**Comment by lialosiu** [comment]
推荐先mtd刷上 [这个](http://www.right.com.cn/Forum/thread-150908-1-1.html) u-boot，然后想怎么刷就怎么刷~

**Comment by xiaooloong** [comment]
mtd -r write 固件.bin firmware

**Comment by ic0xgkk** [comment]
sysupgrade -n -F xxx.bin或者你直接从uboot刷也成

**Comment by jiangzhouq** [comment]
sysupgrade -n -F xxx.bin   刷了之后开机一直卡在第一个灯常亮，是怎么回事？
