### ISSUE TITLE
不能翻墙啊

### ISSUE THREAD

**Issue by henryhwang** [rssnsj/openwrt-hc5761#11]
用你的固件，刷了极1S。路由工作正常，只是不能翻墙啊。有什么特别的设置吗？

**Comment by PeterCxy** [comment]
翻墙又不是固件自带的功能。。
Sent using CloudMagic
On Sun, Jan 25, 2015 at 8:57 PM, Henry H Wang notifications@github.com wrote:用你的固件，刷了极1S。路由工作正常，只是不能翻墙啊。有什么特别的设置吗？

**Comment by henryhwang** [comment]
这个固件是加了翻墙的packages的啊
