### ISSUE TITLE
求问一下HC5661A的SD卡驱动怎么适配？

### ISSUE THREAD

**Issue by yujincheng08** [rssnsj/openwrt-hc5761#126]
我折腾了几天，把HC5661A的WiFi和Led给适配了，然而SD卡驱动死活安不上去。强行安上去会死LAN口和WAN口。所以想请教一下po主。
我的项目地址：https://github.com/yujincheng08/HC5661A.dts
里面有部分内容是参考了po主的内容的。非常感谢！

**Comment by rssnsj** [comment]
赞！屌的不要不要的~

**Comment by gigibox** [comment]
同问, 我也折腾了几天了, 搞不好.. 加mtk-sd驱动, 网卡就剩port0能用了

**Comment by gigibox** [comment]
[#resolved](https://github.com/yujincheng08/HC5661A.dts/issues/2)

**Comment by yujincheng08** [comment]
Thx to @gigibox
