### ISSUE TITLE
HC5661能用么？

### ISSUE THREAD

**Issue by lantsing** [rssnsj/openwrt-hc5761#15]
下载说明里说极1S和极2通用，但是下载只有openwrt-ramips-mt7620a-hiwifi-hc5761-squashfs-sysupgrade.bin文件，没有HC5661的，刷入极1S会无法开机。

**Comment by rssnsj** [comment]
固件是通用的，因为极1S和极2硬件设计基本一样，只是极2多个5G芯片。
