### ISSUE TITLE
极2用户一直以来有一个问题

### ISSUE THREAD

**Issue by xiaooloong** [rssnsj/openwrt-hc5761#16]
安全TCP连接容易断开的问题

以前是从一个https的svn仓库里update时，会遇到错误，提示ssl传输失败什么来着的错误……
使用windows远程桌面（带网络级别身份验证）从wan连接到lan里面的电脑时（防火墙配置端口转发），也出现了远程桌面不断断开，提示“数据加密错误”……

并且，wan和lan之间转发时，速度并不是很高。

是否是因为NAT的bug导致转发速率不高以及造成了加密传输时的数据损坏呢？

**Comment by xiaooloong** [comment]
百度盘客户端上传文件频繁出现错误“本地文件发生改变，上传失败”

**Comment by ic0xgkk** [comment]
你被百度盘和谐啦

**Comment by xiaooloong** [comment]
ethtool -K eth0 gso off gro off
感谢v大:D
