### ISSUE TITLE
有办法支持硬件NAT么？

### ISSUE THREAD

**Issue by xiaooloong** [rssnsj/openwrt-hc5761#17]
http://www.anz.ru/files/mediatek/MT7620_Datasheet.pdf
看到文档里说支持
“Hardware NAT with IPv6 and 2 Gbps wired speed”
请教一下如何支持呢？

**Comment by swshan** [comment]
我认为厂家没有释放出GPL 的代码 应该是不可能了 即使有 移植也是问题
所以基本上就不要抱有这个想法了
性能优化什么的可以考虑一下

华硕路由固件的地址？
http://ftp.tekwind.co.jp/pub/asustw/wireless/
