### ISSUE TITLE
最近不知道啥情况。数据传输经常出错。例如下载个文件，是错误的，CRC 对不上。

### ISSUE THREAD

**Issue by laincat** [rssnsj/openwrt-hc5761#2]
浏览网页，图片会有一两张是 花掉的。

下载 文件，基本上 都是 各种解压文件错误。。。

头都大了，不会是我把路由弄坏了？

就只用了 “不死 U-Boot” 然后各种刷来刷去。。。折腾得头大。

都准备跟着 大大的 OpenWrt Patch 自己 编译 看看。。。

**Comment by laincat** [comment]
刷 PandoraBox-R2-ralink-ji2-r586-20140828-alpha.bin 就正常。。。

**Comment by rssnsj** [comment]
数据错误问题是驱动LRO支持部分有bug造成的，解决办法是禁用它，在 /etc/rc.local 里增加：
ethtool -K eth0 tso off gso off gro off sg off

另外，看来trunk还是不靠谱，master分支我已经切换为 barrier_breaker 了，trunk放到 chaos_breaker 分支。
