### ISSUE TITLE
hc5761上配置VPN无法通过VPN来上网，有BUG。其他同仁测试是否正常？

### ISSUE THREAD

**Issue by winzingggggg** [rssnsj/openwrt-hc5761#26]
hc5761上配置VPN无法通过VPN来上网，有bug，单独拿来用是好的，待其他同仁测试是否正常，我的联系方式 QQ:58036298  请注明 是通过github

**Comment by xiaooloong** [comment]
手动mentohust连接校园网+使用luci配置的l2tp vpn电信宽带使用正常

**Comment by winzingggggg** [comment]
能说具体点吗

xiaooloong notifications@github.com于2015年3月22日星期日写道：

**Comment by xiaooloong** [comment]
学校的电信商业宽带是连上校园网之后再使用电信的vpn连接的
后来发现是无IPSec的l2tp vpn，所以直接就在luci上配置一个新接口，填上电信的vpn服务器、帐号密码就连上了。
