### ISSUE TITLE
GFW-List失效

### ISSUE THREAD

**Issue by acisky** [rssnsj/openwrt-hc5761#27]
GFW-List自动代理失效，换成所有非天草IP才能用

另外SWAP不能设置缓存大小，这是openwrt的bug吗

**Comment by timwangdev** [comment]
同, Mac 本机开 SS 没有问题, 一换路由器的 SS 就各种跳 SSL 证书错误, 解析失败等等

**Comment by acisky** [comment]
已经解决
安全DNS换成114.114.114.114就可以了
