### ISSUE TITLE
通过 luci 配置多个 SSID 时，写入的配置有重复的网络接口名 (ifname=rai0)，导致重启后无线启动失败

### ISSUE THREAD

**Issue by moontide** [rssnsj/openwrt-hc5761#29]
通过 luci 添加第二个 2.4G 的无线设备时，保存并应用，此时设备是能启动起来的。

但是看一下 /etc/config/wireless 时，新加的网络接口设备名为 rai0，这个名称与 5G 的 ifname 是相同的，这样的话，如果重启wifi (执行 wifi up 命令)，无线就启动不了了

不知道是否与多个 wifi-device 有关，我家里的路由器只有 2.4G 的 wifi 设备，通过 luci 配置时，ifname 是自动从 wlan0-1 递增的

**Comment by madwyn** [comment]
我也碰到同样的问题（#44）。所以不用 luci 就不会有这个问题咯？
