### ISSUE TITLE
Google Play在ss下无法下载应用

### ISSUE THREAD

**Issue by Evolto2019** [rssnsj/openwrt-hc5761#30]
使用的是gfwlist自动代理，安全DNS端口是1053,开启了通过ss隧道走支持TCP的DNS。手机上的play商店下载应用进度条闪几下就没了，怀疑是ss没有代理Google Play用的5228端口？

**Comment by wenbo828** [comment]
我才刷的路由器，也发现这个问题，不过没你研究的这么深，打开play可以，就是不能下载。

**Comment by foretony5211** [comment]
加入gvt0.com、gvt1.com、gvt2.com、gvt3.com，就可以了

**Comment by wenbo828** [comment]
这是什么站点？搜索不到相关有用结果？

**Comment by wenbo828** [comment]
看了一下whois是属于Google的

**Comment by lcsxia** [comment]
googles.com
googleapis.cn
gvt0.com
gvt1.com
gvt2.com
gvt3.com
在路由器ss中把这几个网址加入黑名单后，可以打开google paly了，但是无法下载。但开全局模式可以下载。肯定还有什么域名被阻挡了，有会抓包的同学研究下
