### ISSUE TITLE
aria2极端不稳定。

### ISSUE THREAD

**Issue by gnwzkd** [rssnsj/openwrt-hc5761#31]
软件包的来源是默认的软件源，具体表现是，开启进程没问题，一旦使用RPC操作任务（添加/暂停/删除），就会有很高几率报错并退出，已知3种报错分别是Segmentation falt、Illegal instruction、Bus error，自己编译了aria2以及它的依赖包（即aria2、libc、zlib、libxml2、libstdcpp、libopenssl）强制安装之后问题不再重现，我挂载了一张格成ext4的16G SD卡作extroot，我没有在之前的固件里使用过extroot，不知是否与此有关。

**Comment by jh10001** [comment]
差不多的问题，除了这些错误还有可能报浮点错误之类。我也挂载了一张16G的SD卡一个ext4分区作extroot。只要是放在卡里的程序都有这个问题，如果直接编译进固件就正常，不用extroot，官方软件源预编译的包也正常，还没有测试extroot，自己编译程序的情况。试了php5、nignx、mysql，都是这样。

**Comment by jh10001** [comment]
已经测试，自己编译的程序，只要是装在卡里，同样会出错。

**Comment by gnwzkd** [comment]
我也发现了，而且，运行一段时间，卡上的数据会出问题，只有取下卡才能开机，否则无限重启，能够读卡，但重新复制/overlay下的内容到卡里重启依然不能开机，只有格卡才能继续使用，如此循环。
