### ISSUE TITLE
如何获取MTK的闭源驱动并编译进sysupgrade.bin

### ISSUE THREAD

**Issue by jimmysitu** [rssnsj/openwrt-hc5761#33]
如何编译出像项目Release那样的包含MTK闭源驱动的镜像？

**Comment by lparam** [comment]
把png后缀名去掉
![kmod-mt7610e_3 10 49-1_ramips_24kec ipk](https://cloud.githubusercontent.com/assets/657233/7296359/739c8daa-e9f1-11e4-88b7-8601ae324010.png)

**Comment by jimmysitu** [comment]
不太明白什么意思？
能细聊一下吗？

web@jimmystone.cn
QQ 44508648

------------------ 原始邮件 ------------------
发件de人: "Ken"notifications@github.com;
发送时间: 2015年4月23日(星期四) 晚上7:48
收件人: "rssnsj/openwrt-hc5761"openwrt-hc5761@noreply.github.com; 
抄送: "web"web@jimmystone.cn; 
主题: Re: [openwrt-hc5761] 如何获取MTK的闭源驱动并编译进sysupgrade.bin (#33)

把png后缀名去掉

**Comment by lparam** [comment]
你先在release下载包含MTK闭源驱动的镜像，把7610e相关文件提取出来， 再放到base-files相关文件夹里，然后编译就行了。

**Comment by lparam** [comment]
btw: 7610e对应的设备名叫rai0, 你要配置好led，要不5G那个灯不会亮。
