### ISSUE TITLE
中继时克隆mac会使无线功能无法使用。

### ISSUE THREAD

**Issue by xuexingmalili** [rssnsj/openwrt-hc5761#35]
ap-sta模式，wwan mac显示00:00:00:00:00:00,但可以上网，上级显示是ralink的mac.克隆mac后会使无线无法开启。直接改/etc/config/network后，wwan可以显示对应的mac,但上级路由还是原来的ralink mac.

**Comment by rssnsj** [comment]
没错，不要尝试更改sta模式下wlan接口的mac，wifi协议对此有限制，否则数据包无法发送出去。
