### ISSUE TITLE
Google Play无法下载，需要增加Google的CDN

### ISSUE THREAD

**Issue by ojdev** [rssnsj/openwrt-hc5761#37]
代理监控后发现GooglePlay下载链接的是
gvt0.com
gvt1.com
gvt2.com
gvt3.com
gvt4.com
gvt5.com
这几个据说是GoogleCDN的地址，需要添加到域名列表里才能下载，但是有的时候还是很慢，不知道是为什么。

**Comment by rssnsj** [comment]
多谢，回头加进去。
