### ISSUE TITLE
请问这个怎么编译工具链？

### ISSUE THREAD

**Issue by mlkt** [rssnsj/openwrt-hc5761#38]
我想编译一个gccgo 我想编译一个go写的程序 官方的sdk包make的时候显示：
This source tree cannot be used for building firmware.
If you mean building an OpenWrt package, please follow:
1. Write a package description following the OpenWrt formats, and put or link the directory under 'package/' directory;
2. Execute 'make menuconfig', and select your package with '<M>';
3. Run the following command under current direcory:
   make package/<package_dir_name>/compile V=s
   Please note that <package_dir_name> is the directory name under 'package/'.
   For detailed instructions please refer to OpenWrt official website:
   http://wiki.openwrt.org/doc/devel/packages

**Comment by rssnsj** [comment]
请咨询官方。
