### ISSUE TITLE
有线网+VPN上不了网

### ISSUE THREAD

**Issue by xiaooloong** [rssnsj/openwrt-hc5761#40]
网络interface中添加l2tp的vpn，默认路由，并为一些IP添加了路由使用默认wan接口路由

配置完成之后，2.4G和5G的wifi访问一切正常

使用有线lan接口访问不经过vpn的流量正常，也能打开路由器后台界面

使用有线lan接口访问经过vpn的流量就访问不了了，但是ping这些经过vpn路由的ip是能ping通的

比如百度是经过vpn路由的，使用有线网可以ping通百度，但是使用浏览器无法打开百度的网页，并且在浏览器尝试打开百度的过程中，可以看到ping百度的延迟从几十毫秒到上千毫秒一直在跳

**Comment by winzingggggg** [comment]
我和你遇到的情况是一样的，刷了很多版本的都不行，感觉是编译的时候出了问题。在这边也提出了疑问，没有人回答，如果你知道了原因，请告诉我。谢谢
