### ISSUE TITLE
使用SS 无法上FB 等网站

### ISSUE THREAD

**Issue by ningxiaoixao** [rssnsj/openwrt-hc5761#42]
极2  用了SS 没有用facebook无法上

**Comment by ic0xgkk** [comment]
DNS缓存清了麽？我的都可以啊

**Comment by zzswang** [comment]
请问清本机DNS缓存 还是 路由器上的？

**Comment by zzswang** [comment]
和楼主相同的问题。可以上google，但不能上 其他网站。 不知该怎么设置，目前全部默认配置。

**Comment by zzswang** [comment]
是不是需要做什么配置？ 求教程

**Comment by zzswang** [comment]
![qq20150606-1 2x](https://cloud.githubusercontent.com/assets/1524745/8019287/669b6ac2-0c79-11e5-812e-3d1415508cac.png)

**Comment by 0xshawn** [comment]
极路由2 HC5761 有同样情况，Google, Gmail没有问题，其他如FB, Twitter, Youtube无法正常访问

**Comment by ningxiaoixao** [comment]
这个问题已经找到了解决方法 为以后来的人给出一个解决方案.
这个问题是因为DNS被污染了.
所以.如果是在路由器中使用.请使用 chinadns openwrt 查找解决方案

**Comment by zzswang** [comment]
大神 再问一下  我看有新的release出来，已经解决这个问题了么？

另外尝试自己安装了一下chinadns  按照网上的教程，死活整不上去，感觉本地有一些配置有冲突，搞不定呀，大神能否在固件中加入 chinadns？
