### ISSUE TITLE
2.4G 做 Client 有时会导致 2.4G 被改成 5G

### ISSUE THREAD

**Issue by madwyn** [rssnsj/openwrt-hc5761#44]
HC5761

比如我的现在就成了：

Generic WEXT 802.11 (mt7610e)
Channel: 44 (? GHz) | Bitrate: 433.5 Mbit/s

Generic WEXT 802.11 (radio0)
Channel: 44 (? GHz) | Bitrate: 433.5 Mbit/s

**Comment by rssnsj** [comment]
应该已经修复了，试试最新版吧。

**Comment by hero18688** [comment]
试过最新版也有此问题

**Comment by LinEvil** [comment]
你好，我遇到了相同的问题（最新版本的固件），请问你解决了吗？
