### ISSUE TITLE
建议：把极路由加入openwrt官方代码里。小米路由已经加入了……

### ISSUE THREAD

**Issue by shaunthegeek** [rssnsj/openwrt-hc5761#50]
刚clone了openwrt Chaos Calmer (trunk)官方代码：https://dev.openwrt.org/wiki/GetSource

```
git clone git@git.coding.net:openwrtio/openwrt.git
git clone git://git.openwrt.org/openwrt.git
cd openwrt
make menuconfig
```

选了Ralink和MT7620，Target Profile里出现了小米路由 Xiaomi MiWiFi Mini，如图：
![2015-07-09 22 11 52](https://cloud.githubusercontent.com/assets/4971414/8597484/37c59ce4-2688-11e5-9bfc-8e6520e2d5b1.png)
![2015-07-09 22 12 05](https://cloud.githubusercontent.com/assets/4971414/8597487/3ca39df6-2688-11e5-8357-2ac00704c50e.png)

建议：把极路由也提交到openwrt官方代码里，便于开发者编译。

**Comment by madwyn** [comment]
赞同，贡献到主干，少好多麻烦

**Comment by misakaok** [comment]
这个必须赞同

**Comment by yasteora** [comment]
赞同，但是不知道 5Gwifi 驱动非开源是否会影响？

**Comment by rssnsj** [comment]
确实很想，我也向openwrt官方提交过，不过没有精力跟进patch的后续进展，哪位兄弟能帮这个忙？

**Comment by shaunthegeek** [comment]
嗯。最近没怎么折腾路由器了。有空时研究下怎么提交到openwrt官方。

各位童鞋有空都研究研究啊。
