### ISSUE TITLE
极2WIFI时常断网

### ISSUE THREAD

**Issue by xiaooloong** [rssnsj/openwrt-hc5761#53]
前两天刷了7.20的固件，5G和2.4G的wifi都时常出现能连接但是无网络（能连上WIFI，但是无法ping通路由器，无法访问网络）

请问这种情况，可以通过重启某个组件修复么？

**Comment by yx1989** [comment]
同遇到这个问题，在高速下载的时候很容易复现。

重启路由器就好了。
