### ISSUE TITLE
新版极1s HC5661A 是MT 7628A 芯片的，期待支持哇

### ISSUE THREAD

**Issue by shaunthegeek** [rssnsj/openwrt-hc5761#54]
新版极1s HC5661A 是MT 7628A 芯片的，在 http://rssn.cn/ 里面也看见 HC5661A 和 HC5761A的固件下载了，期待支持编译哇，万分感谢

**Comment by hdstar2009** [comment]
是啊，现在能买到的基本都是5661a了

**Comment by rssnsj** [comment]
很快就会支持了，正在做适配~~

**Comment by ETiV** [comment]
今天买了个极贰, 结果真是二...

硬件型号: HiWiFi HC5761A

```
# cat /proc/cpuinfo
system type     : Ralink MT7628 ver:1, eco:2
machine         : HiWiFi Wireless HC5761s Board
processor       : 0
cpu model       : MIPS 24KEc V5.5
BogoMIPS        : 380.92
......
```

Google 搜 openwrt HC5761A 只有这一个结果有用...
所以我想问问有没有什么进展...

还有, 作为新人, 想问问 uboot / breed 这个, 是不是只要CPU型号相同, 是不是可以通刷的?

**Comment by raiscui** [comment]
期待 HC5761A 的支持

**Comment by nsecgo** [comment]
现在是2016年3月5日16:09:58，HC5761A 好像还是没支持，有没有好心人告诉我一下
