### ISSUE TITLE
5G wifi 无法设置密码

### ISSUE THREAD

**Issue by Felix-Bao** [rssnsj/openwrt-hc5761#56]
我刷了极2的新ROM，openwrt-ramips-mt7620a-hiwifi-hc5761-squashfs-sysupgrade.bin，7月30日版本。5G wifi无法设置密码，总是提示“一个或多个选项值有误！”。
![cap](https://cloud.githubusercontent.com/assets/13605862/9024231/fa329f3c-38f5-11e5-9af0-7942bda7e64f.PNG)

**Comment by yasteora** [comment]
你好请问一下，你是不是保留配置文件升级了呢，如果是的话恢复出厂在试试看，如果不嫌麻烦的顺便把配置文件发给我一份吧 我也有同样的错误
那个设置密码有个 更换密码的时间 单位是秒 在 密码上面那一栏

**Comment by Felix-Bao** [comment]
我又刷了个7月20号的版本，这回是没保留配置文件升级的。虽然5G是能用了，但很多原来有的选项没有了，比如信道选择之类的。而且我的aria2从我装它开始就只支持http下载，不支持bt和ed2k，不知道是不是我配置的问题。
2015年8月5日 下午11:02于 "yasteora" notifications@github.com写道：

**Comment by yasteora** [comment]
aria2 我没用不清楚，不过5Gwifi 配置文件改了 所以很多选项就变了 好像有bug报 2.4Gwifi的 信道不见了，我也是如此

**Comment by rssnsj** [comment]
应该已经改好了，大家试试最新版本吧。
