### ISSUE TITLE
建议将shadows-libev 换成shadowsocks-libev-spec，并加入china-DNS

### ISSUE THREAD

**Issue by yasteora** [rssnsj/openwrt-hc5761#57]
shadowsocks-libev-spec 有 ip 控制（选择局域网那些设备走代理那些不走），而且可以开启
udp转发 解决dns污染问题 ，配合china-dns 非常好用。

**Comment by rssnsj** [comment]
shadowsocks-tools 这个package就是做IP、域名控制的。

**Comment by yasteora** [comment]
额 你好，我说的不是 通过 dnsmasq ipset 分组ip，
是指的是局域网 特定设备 走不走 代理 控制。

**Comment by rssnsj** [comment]
有一个隐藏的选项 covered_subnets，默认为LAN口IP段，但这个是白名单。可以手动修改 /etc/config/minivtun ，增加类似如下的选项：

```
option covered_subnets '172.20.0.0/24 192.168.0.0/24 10.1.0.0/16'
```
