### ISSUE TITLE
最新编译好的固件怎么没有hc5661

### ISSUE THREAD

**Issue by 27747** [rssnsj/openwrt-hc5761#59]
我只能找到6月份的

**Comment by yasteora** [comment]
hc56x1  通用的，作者有说明的，都 发布的，也注明了。

**Comment by rssnsj** [comment]
hc5761是极1S、极2通用的

发件人:  P777777777 notifications@github.com
答复:  rssnsj/openwrt-hc5x61
<reply+003213a65eeae33d9d405d5e03c64c46eb8ea593e316533f92cf0000000111f32d369
2a169ce0621a77d@reply.github.com>
日期:  2015年8月25日 星期二 03:06
至:  rssnsj/openwrt-hc5x61 openwrt-hc5x61@noreply.github.com
主题:  [openwrt-hc5x61] 最新编译好的固件怎么没有hc5661 (#59)

我只能找到6月份的

—
Reply to this email directly or view it on GitHub
https://github.com/rssnsj/openwrt-hc5x61/issues/59 .
