### ISSUE TITLE
使用带驱动的固件,5GWIFI仍然无法使用。

### ISSUE THREAD

**Issue by LeXwDeX** [rssnsj/openwrt-hc5761#64]
我是 HC5761（极2）（MT7610E）从「 http://rssn.cn/roms/ 」这个地方下载的编译过的固件，

但是仍然无法启动5Gwifi，根据信息判断是没有驱动加载的。

**Comment by sunsan05** [comment]
我使用的是编译过的固件，通过ROOT之后刷进去的。固件名称是openwrt-ramips-mt7620a-hiwifi-hc5761-squashfs-sysupgrade.bin 我是HC5761 极2

**Comment by sunsan05** [comment]
-看到支持5Gwifi但是仍然无法启动，…然后小白菜也不懂如何安装那个M什么的WIFI驱动，，所以等大神回复了QAQ

**Comment by sunsan05** [comment]
我知道了。我用的固件不是mt7610e的WIFI固件。我去找找看。
