### ISSUE TITLE
开启ChinaDNS的时候ss不能代理翻墙

### ISSUE THREAD

**Issue by Ardentwheel** [rssnsj/openwrt-hc5761#69]
未使用ChinaDNS的时候，ss正常能代理网站
使用以下设置后就不能翻墙了
如果是设置问题请指出，谢谢！（使用ChinaDNS是因为ss代理后的国内网站打开都很慢）
###### ChinaDNS：

启用双向过滤
本地端口            5353
国内路由表         /etc/chinadns_chnroute.txt
上游服务器        114.114.114.114,192.168.0.11,208.67.222.222:443,8.8.8.8
###### ss：

代理模式为        GFW-List
安全DNS           8.8.8.8
安全DNS端口    53
DNS使用TCP    打了勾
###### DHCP/DNS：

DNS转发           127.0.0.1#5353
忽略解析文件     打了勾

**Comment by rssnsj** [comment]
ChinaDNS的问题请直接咨询该插件作者。
