### ISSUE TITLE
pdnsd端口与dnsmasq冲突导致不能启动

### ISSUE THREAD

**Issue by Ardentwheel** [rssnsj/openwrt-hc5761#7]
刚刷完机，dnsmasq是存在的没有pdnsd，重启后就有pdnsd没有dnsmasq了，
只有关闭pdnsd了dnsmasq才能启动，
/etc/pdnsd.conf 中没有端口号的设置，导致启动时使用默认53端口与dnsmasq冲突。

**Comment by zhangll** [comment]
我也遇到了这个情况，我在/etc/pdnsd.conf中修改了pdnsd的端口  server_port = 1053;
然后把dnsmasq 配置/var/etc/dnsmasq-go.d/01-pollution.conf 的引用都从7453替换成了1053。
一直搞不懂这个7453是从哪里来的。

**Comment by rssnsj** [comment]
/etc/init.d/ss-redir.sh  里面封装了对 pdnsd 的调用，不需要自己改端口。
