### ISSUE TITLE
软件包问题

### ISSUE THREAD

**Issue by swshan** [rssnsj/openwrt-hc5761#8]
openwrt 14.07 的软件包似乎安装不了

安装 tc 的时候
出错提示
Collected errors:
- satisfy_dependencies_for: Cannot satisfy the following dependencies for tc:
-  kernel (= 3.10.49-1-3df3ab26a49a04478a9633bf83827ca3) \* 
- opkg_install_cmd: Cannot install package tc.

**Comment by Ardentwheel** [comment]
固件的内核不匹配。用自己编译的软件包吧，还可以离线。

**Comment by swshan** [comment]
嗯 我知道是不匹配的问题了 而且似乎有一个shell 命令可以控制后缀的数字不生成

**Comment by lantsing** [comment]
opkg install /tmp/xxx.ipk --force-depends可以解决安装问题，不过我想编译到固件里，应该如何操作？

**Comment by rssnsj** [comment]
tc 已经添加到固件里了。
