### ISSUE TITLE
为何5G的信道设置里只有2.4G的信道

### ISSUE THREAD

**Issue by kenvix** [rssnsj/openwrt-hc5761#80]
![qq 20151031225152](https://cloud.githubusercontent.com/assets/4546175/10864235/94289fba-8022-11e5-8b89-78f6d3757efe.png)
如图，刚刷了最新版本的固件，恢复出厂设置也是如此（HC5861）  
虽然当前信道是36，,但是修改设置后信道就变成1了...

**Comment by LeXwDeX** [comment]
你设定的bgn 5G是ac
